# -*- coding: utf-8 -*-
"""AUTOHEAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gBGUV26LXWTG73Soz1xa5jisLBqKtwth
"""

# AutoHeal - Complete Experiment Script
# ======================================
# Run this single file to get ALL results for the IEEE paper.

# What this script does:
#   1. Trains Random Forest on Breast Cancer + Iris datasets
#   2. Simulates concept drift (Gaussian noise injection)
#   3. Runs self-healing cycle: monitor -> detect -> retrain -> recover
#   4. Repeats across 5 independent runs for statistical validity
#   5. Compares AutoHeal vs No-Monitoring vs Scheduled Retraining
#   6. Generates and saves all result graphs as PNG files
#   7. Prints a full results summary table

# Requirements:
#   pip install scikit-learn pandas matplotlib numpy

# Usage:
#   python autoheal_experiment.py

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import os
import warnings
warnings.filterwarnings("ignore")

from sklearn.datasets import load_breast_cancer, load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# -- Output folder -------------------------------------------------------------
os.makedirs("results", exist_ok=True)

print("=" * 65)
print("  AutoHeal - Self-Healing ML Pipeline")

print("=" * 65)


# ==================================================================
# HELPER: simulate one full self-healing cycle for a dataset
# ==================================================================
def run_autoheal_cycle(X, y, run_seed, window=50, threshold=0.75,
                        consec_k=3, noise_mean=5.0, noise_std=3.0,
                        n_clean=80, n_drift=80, n_recovery=80):
    """
    Runs the full AutoHeal cycle:
      Phase 1 - clean data  (model predicts well)
      Phase 2 - drifted data (accuracy drops)
      Phase 3 - recovery data (after auto-retrain)

    Returns a dict with all metrics and the full accuracy log.
    """

    # -- Train initial model ---------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=run_seed, stratify=y
    )
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    baseline_acc = accuracy_score(y_test, model.predict(X_test))

    # -- Prediction buffer -----------------------------------------
    pred_buffer = []   # stores (true, predicted) tuples
    accuracy_log = []  # stores (phase, rolling_acc) tuples

    def rolling_accuracy():
        if len(pred_buffer) < window:
            return 1.0
        recent = pred_buffer[-window:]
        return np.mean([int(t == p) for t, p in recent])

    # -- Phase 1: Clean predictions --------------------------------
    rng = np.random.RandomState(run_seed * 100)
    for _ in range(n_clean):
        idx = rng.randint(len(X_test))
        pred = model.predict(X_test[idx].reshape(1, -1))[0]
        pred_buffer.append((y_test[idx], pred))
        if len(pred_buffer) >= window:
            accuracy_log.append(("clean", rolling_accuracy()))

    # -- Phase 2: Drifted predictions -----------------------------
    drift_trigger_idx = None
    fail_count = 0
    for i in range(n_drift):
        idx = rng.randint(len(X_test))
        noisy_x = X_test[idx] + rng.normal(noise_mean, noise_std, X_test[idx].shape)
        pred = model.predict(noisy_x.reshape(1, -1))[0]
        pred_buffer.append((y_test[idx], pred))
        if len(pred_buffer) >= window:
            acc = rolling_accuracy()
            accuracy_log.append(("drift", acc))
            # Drift detection logic
            if acc < threshold:
                fail_count += 1
                if fail_count >= consec_k and drift_trigger_idx is None:
                    drift_trigger_idx = len(accuracy_log) - 1
            else:
                fail_count = 0

    min_drift_acc = min(
        [a for ph, a in accuracy_log if ph == "drift"], default=baseline_acc
    )

    # -- Retrain on fresh clean data -------------------------------
    X_tr2, X_te2, y_tr2, y_te2 = train_test_split(
        X, y, test_size=0.2, random_state=run_seed + 50, stratify=y
    )
    new_model = RandomForestClassifier(n_estimators=100, random_state=42)
    new_model.fit(X_tr2, y_tr2)
    retrain_acc = accuracy_score(y_te2, new_model.predict(X_te2))

    # Deploy if better (with tolerance 0.02)
    deployed_model = new_model if retrain_acc >= baseline_acc - 0.02 else model
    redeployed = retrain_acc >= baseline_acc - 0.02

    # -- Phase 3: Recovery predictions ----------------------------
    for _ in range(n_recovery):
        idx = rng.randint(len(X_test))
        pred = deployed_model.predict(X_test[idx].reshape(1, -1))[0]
        pred_buffer.append((y_test[idx], pred))
        if len(pred_buffer) >= window:
            accuracy_log.append(("recovery", rolling_accuracy()))

    recovery_acc = np.mean(
        [a for ph, a in accuracy_log if ph == "recovery"]
    ) if any(ph == "recovery" for ph, a in accuracy_log) else 0.0

    return {
        "baseline_acc":      round(baseline_acc, 4),
        "min_drift_acc":     round(min_drift_acc, 4),
        "retrain_acc":       round(retrain_acc, 4),
        "recovery_acc":      round(recovery_acc, 4),
        "drift_trigger_idx": drift_trigger_idx,
        "redeployed":        redeployed,
        "accuracy_log":      accuracy_log,
    }


# ==================================================================
# EXPERIMENT 1 - BREAST CANCER DATASET (5 runs)
# ==================================================================
print("\n" + "─" * 65)
print("  EXPERIMENT 1: Breast Cancer Wisconsin Diagnostic Dataset")
print("─" * 65)

bc_data = load_breast_cancer()
X_bc, y_bc = bc_data.data, bc_data.target

bc_results = []
for run in range(5):
    result = run_autoheal_cycle(X_bc, y_bc, run_seed=run,
                                 noise_mean=5.0, noise_std=3.0)
    bc_results.append(result)
    print(f"  Run {run+1}/5 | Baseline: {result['baseline_acc']:.2%} | "
          f"Min Drift: {result['min_drift_acc']:.2%} | "
          f"Recovery: {result['recovery_acc']:.2%} | "
          f"Retrained: {'YES' if result['redeployed'] else 'NO'}")

bc_df = pd.DataFrame([{k: v for k, v in r.items() if k != "accuracy_log"}
                       for r in bc_results])

# Compute stats
bc_stats = {
    "baseline_mean":  bc_df["baseline_acc"].mean(),
    "baseline_std":   bc_df["baseline_acc"].std(),
    "drift_mean":     bc_df["min_drift_acc"].mean(),
    "drift_std":      bc_df["min_drift_acc"].std(),
    "recovery_mean":  bc_df["recovery_acc"].mean(),
    "recovery_std":   bc_df["recovery_acc"].std(),
    "retrain_mean":   bc_df["retrain_acc"].mean(),
}

print(f"\n  Summary (mean \u00b1 std across 5 runs):")
print(f"  Baseline accuracy  : {bc_stats['baseline_mean']:.2%} \u00b1 {bc_stats['baseline_std']:.2%}")
print(f"  Min drift accuracy : {bc_stats['drift_mean']:.2%} \u00b1 {bc_stats['drift_std']:.2%}")
print(f"  Recovery accuracy  : {bc_stats['recovery_mean']:.2%} \u00b1 {bc_stats['recovery_std']:.2%}")
print(f"  Successful redeploys: {bc_df['redeployed'].sum()}/5")


# ==================================================================
# EXPERIMENT 2 - IRIS DATASET (5 runs)
# ==================================================================
print("\n" + "─" * 65)
print("  EXPERIMENT 2: Iris Dataset")
print("─" * 65)

iris_data = load_iris()
X_iris, y_iris = iris_data.data, iris_data.target

iris_results = []
for run in range(5):
    result = run_autoheal_cycle(X_iris, y_iris, run_seed=run,
                                 window=30, noise_mean=3.0, noise_std=2.0,
                                 n_clean=60, n_drift=60, n_recovery=60)
    iris_results.append(result)
    print(f"  Run {run+1}/5 | Baseline: {result['baseline_acc']:.2%} | "
          f"Min Drift: {result['min_drift_acc']:.2%} | "
          f"Recovery: {result['recovery_acc']:.2%} | "
          f"Retrained: {'YES' if result['redeployed'] else 'NO'}")

iris_df = pd.DataFrame([{k: v for k, v in r.items() if k != "accuracy_log"}
                         for r in iris_results])

iris_stats = {
    "baseline_mean":  iris_df["baseline_acc"].mean(),
    "baseline_std":   iris_df["baseline_acc"].std(),
    "drift_mean":     iris_df["min_drift_acc"].mean(),
    "drift_std":      iris_df["min_drift_acc"].std(),
    "recovery_mean":  iris_df["recovery_acc"].mean(),
    "recovery_std":   iris_df["recovery_acc"].std(),
}

print(f"\n  Summary (mean \u00b1 std across 5 runs):")
print(f"  Baseline accuracy  : {iris_stats['baseline_mean']:.2%} \u00b1 {iris_stats['baseline_std']:.2%}")
print(f"  Min drift accuracy : {iris_stats['drift_mean']:.2%} \u00b1 {iris_stats['drift_std']:.2%}")
print(f"  Recovery accuracy  : {iris_stats['recovery_mean']:.2%} \u00b1 {iris_stats['recovery_std']:.2%}")
print(f"  Successful redeploys: {iris_df['redeployed'].sum()}/5")


# ==================================================================
# EXPERIMENT 3 - BASELINE COMPARISON
# ==================================================================
print("\n" + "─" * 65)
print("  EXPERIMENT 3: AutoHeal vs No-Monitor vs Scheduled Retrain")
print("─" * 65)

X_tr, X_te, y_tr, y_te = train_test_split(
    X_bc, y_bc, test_size=0.2, random_state=0, stratify=y_bc
)
rng = np.random.RandomState(42)

def make_noisy(x): return x + rng.normal(5.0, 3.0, x.shape)

# - Method 1: No monitoring ------------------------------------------
m_base = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr, y_tr)
no_mon_correct = []
for _ in range(100):
    idx = rng.randint(len(X_te))
    pred = m_base.predict(make_noisy(X_te[idx]).reshape(1, -1))[0]
    no_mon_correct.append(int(pred == y_te[idx]))
no_mon_acc = round(np.mean(no_mon_correct), 4)

# - Method 2: Scheduled retraining (every 50 predictions) -----------
m_sched = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr, y_tr)
sched_correct = []
for i in range(100):
    if i == 50:
        # Scheduled retrain at midpoint
        m_sched = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr, y_tr)
    idx = rng.randint(len(X_te))
    pred = m_sched.predict(make_noisy(X_te[idx]).reshape(1, -1))[0]
    sched_correct.append(int(pred == y_te[idx]))
sched_acc = round(np.mean(sched_correct), 4)

# - Method 3: AutoHeal ----------------------------------------------
m_ah = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr, y_tr)
ah_correct = []
ah_retrain_count = 0
ah_buffer = []
fail_count = 0
for i in range(100):
    idx = rng.randint(len(X_te))
    noisy_x = make_noisy(X_te[idx])
    pred = m_ah.predict(noisy_x.reshape(1, -1))[0]
    correct = int(pred == y_te[idx])
    ah_correct.append(correct)
    ah_buffer.append(correct)
    if len(ah_buffer) >= 20:
        if np.mean(ah_buffer[-20:]) < 0.75:
            fail_count += 1
            if fail_count >= 3:
                # Retrain on clean data
                m_ah = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr, y_tr)
                ah_retrain_count += 1
                fail_count = 0
        else:
            fail_count = 0
ah_acc = round(np.mean(ah_correct), 4)

print(f"\n  No monitoring accuracy    : {no_mon_acc:.2%}  | Retrains: 0  | Human input: YES")
print(f"  Scheduled retrain accuracy: {sched_acc:.2%}  | Retrains: 1  | Human input: YES")
print(f"  AutoHeal accuracy         : {ah_acc:.2%}  | Retrains: {ah_retrain_count}  | Human input: NO")
print(f"\n  AutoHeal improvement over no-monitoring:    +{(ah_acc - no_mon_acc)*100:.1f} pp")
print(f"  AutoHeal improvement over scheduled retrain: +{(ah_acc - sched_acc)*100:.1f} pp")


# ==================================================================
# CONFUSION MATRIX - Breast Cancer (Run 1, post-retrain)
# ==================================================================
print("\n" + "─" * 65)
print("  Classification Report - Breast Cancer (Run 1, after retrain)")
print("─" * 65)

X_tr1, X_te1, y_tr1, y_te1 = train_test_split(
    X_bc, y_bc, test_size=0.2, random_state=0, stratify=y_bc
)
final_model = RandomForestClassifier(n_estimators=100, random_state=42).fit(X_tr1, y_tr1)
y_pred1 = final_model.predict(X_te1)
print(classification_report(y_te1, y_pred1, target_names=["Malignant", "Benign"]))
cm = confusion_matrix(y_te1, y_pred1)
print(f"  Confusion Matrix:\n  {cm}")


# ==================================================================
# SAVE RESULTS TO CSV
# ==================================================================
bc_df.to_csv("results/breast_cancer_results.csv", index=False)
iris_df.to_csv("results/iris_results.csv", index=False)

comparison_df = pd.DataFrame([
    {"Method": "No monitoring",       "Accuracy During Drift": f"{no_mon_acc:.2%}", "Retrains": 0,              "Human Input": "Yes"},
    {"Method": "Scheduled retraining","Accuracy During Drift": f"{sched_acc:.2%}", "Retrains": 1,              "Human Input": "Yes"},
    {"Method": "AutoHeal (proposed)", "Accuracy During Drift": f"{ah_acc:.2%}",   "Retrains": ah_retrain_count,"Human Input": "No"},
])
comparison_df.to_csv("results/comparison_results.csv", index=False)
print("\n  Results saved to results/ folder.")

# Display dataframes directly instead of saving
print("\nBreast Cancer Results (DataFrame):")
print(bc_df)
print("\nIris Results (DataFrame):")
print(iris_df)
print("\nComparison Results (DataFrame):")
print(comparison_df)


# ==================================================================
# GENERATE ALL FIGURES
# ==================================================================
print("\n" + "─" * 65)
print("  Generating figures...")
print("─" * 65)

# -- Figure 1: Accuracy over time (Breast Cancer, Run 1) ---------
fig1, ax1 = plt.subplots(figsize=(8, 4))
log = bc_results[0]["accuracy_log"]
phases = [ph for ph, _ in log]
accs   = [ac for _, ac in log]
x = list(range(len(log)))

phase_colors = {"clean": "#1D9E75", "drift": "#E24B4A", "recovery": "#185FA5"}
for phase in ["clean", "drift", "recovery"]:
    xs = [i for i, p in enumerate(phases) if p == phase]
    ys = [accs[i] for i in xs]
    ax1.plot(xs, ys, color=phase_colors[phase], linewidth=2,
             label=phase.capitalize())

ax1.axhline(y=0.75, color="#BA7517", linestyle="--", linewidth=1.5,
            label="Drift threshold (75%)")

# Annotate drift trigger point
trigger = bc_results[0]["drift_trigger_idx"]
if trigger:
    ax1.annotate("Retrain\ntriggered",
                 xy=(trigger, accs[trigger]),
                 xytext=(trigger + 6, accs[trigger] - 0.15),
                 fontsize=9, color="#A32D2D",
                 arrowprops=dict(arrowstyle="->", color="#A32D2D"))

# Annotate recovery start
rec_start = next((i for i, p in enumerate(phases) if p == "recovery"), None)
if rec_start:
    ax1.axvline(x=rec_start, color="#185FA5", linestyle=":",
                linewidth=1.5, alpha=0.7)
    ax1.annotate("New model\ndeployed",
                 xy=(rec_start, 0.78),
                 xytext=(rec_start + 5, 0.65),
                 fontsize=9, color="#0C447C",
                 arrowprops=dict(arrowstyle="->", color="#0C447C"))

ax1.set_ylim(0, 1.08)
ax1.set_xlabel("Monitoring cycle", fontsize=11)
ax1.set_ylabel("Rolling accuracy", fontsize=11)
ax1.set_title("Fig 1: Breast Cancer - Accuracy over time", fontsize=11, fontweight="bold")
ax1.legend(fontsize=9, loc="lower right")
ax1.grid(True, alpha=0.3)
# plt.tight_layout()
plt.savefig("results/fig1_accuracy_over_time.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()
plt.close()
# print("  fig1_accuracy_over_time.png saved.") # Commented out as files are not saved

# -- Figure 2: Method comparison bar chart -----------------------
fig2, ax2 = plt.subplots(figsize=(6, 4))
methods = ["No monitoring", "Scheduled\nretraining", "AutoHeal\n(proposed)"]
values  = [no_mon_acc * 100, sched_acc * 100, ah_acc * 100]
colors  = ["#E24B4A", "#EF9F27", "#1D9E75"]

bars = ax2.bar(methods, values, color=colors, width=0.5,
               edgecolor="white", linewidth=1.5)
ax2.axhline(y=75, color="#BA7517", linestyle="--",
            linewidth=1.5, label="Threshold (75%)", zorder=5)

for bar, val in zip(bars, values):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 1.2,
             f"{val:.1f}%", ha="center", fontsize=11, fontweight="bold")

ax2.set_ylim(0, 105)
ax2.set_ylabel("Accuracy (%)", fontsize=11)
ax2.set_title("Fig 2: Method comparison (Breast Cancer)", fontsize=11, fontweight="bold")
ax2.legend(fontsize=9)
ax2.grid(True, alpha=0.3, axis="y")
plt.tight_layout()
plt.savefig("results/fig2_method_comparison.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()
plt.close()
# print("  fig2_method_comparison.png saved.") # Commented out as files are not saved

# -- Figure 3: Breast Cancer - All 5 runs recovery comparison -----
fig3, ax3 = plt.subplots(figsize=(8, 4))
run_labels = [f"Run {i+1}" for i in range(5)]
x_pos = np.arange(5)
width = 0.25

ax3.bar(x_pos - width, bc_df["baseline_acc"] * 100,
        width, label="Baseline", color="#1D9E75", alpha=0.85)
ax3.bar(x_pos,         bc_df["min_drift_acc"] * 100,
        width, label="Min during drift", color="#E24B4A", alpha=0.85)
ax3.bar(x_pos + width, bc_df["recovery_acc"] * 100,
        width, label="After recovery", color="#185FA5", alpha=0.85)

ax3.axhline(y=75, color="#BA7517", linestyle="--", linewidth=1.2,
            label="Threshold (75%)")
ax3.set_xticks(x_pos)
ax3.set_xticklabels(run_labels)
ax3.set_ylim(0, 110)
ax3.set_ylabel("Accuracy (%)", fontsize=11)
ax3.set_title("Fig 3: Breast Cancer - Accuracy across 5 runs", fontsize=11, fontweight="bold")
ax3.legend(fontsize=9)
ax3.grid(True, alpha=0.3, axis="y")
plt.tight_layout()
plt.savefig("results/fig3_bc_five_runs.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()
plt.close()
# print("  fig3_bc_five_runs.png saved.") # Commented out as files are not saved

# -- Figure 4: Dataset comparison (BC vs Iris) --------------------
fig4, ax4 = plt.subplots(figsize=(7, 4))
categories = ["Baseline", "Min Drift", "Recovery"]
bc_vals   = [bc_stats["baseline_mean"]*100,   bc_stats["drift_mean"]*100,   bc_stats["recovery_mean"]*100]
iris_vals = [iris_stats["baseline_mean"]*100, iris_stats["drift_mean"]*100, iris_stats["recovery_mean"]*100]
bc_errs   = [bc_stats["baseline_std"]*100,    bc_stats["drift_std"]*100,    bc_stats["recovery_std"]*100]
iris_errs = [iris_stats["baseline_std"]*100,  iris_stats["drift_std"]*100,  iris_stats["recovery_std"]*100]

xp = np.arange(3)
w  = 0.3
ax4.bar(xp - w/2, bc_vals,   w, yerr=bc_errs,   capsize=4,
        label="Breast Cancer", color="#185FA5", alpha=0.85)
ax4.bar(xp + w/2, iris_vals, w, yerr=iris_errs, capsize=4,
        label="Iris", color="#1D9E75", alpha=0.85)

for i, (bv, iv) in enumerate(zip(bc_vals, iris_vals)):
    ax4.text(i - w/2, bv + 2.5, f"{bv:.1f}%", ha="center", fontsize=9, fontweight="bold")
    ax4.text(i + w/2, iv + 2.5, f"{iv:.1f}%", ha="center", fontsize=9, fontweight="bold")

ax4.axhline(y=75, color="#BA7517", linestyle="--", linewidth=1.2, label="Threshold (75%)")
ax4.set_xticks(xp)
ax4.set_xticklabels(categories, fontsize=11)
ax4.set_ylim(0, 115)
ax4.set_ylabel("Accuracy (%)", fontsize=11)
ax4.set_title("Fig 4: Dataset comparison - Breast Cancer vs Iris (mean \u00b1 std)", fontsize=11, fontweight="bold")
ax4.legend(fontsize=9)
ax4.grid(True, alpha=0.3, axis="y")
plt.tight_layout()
plt.savefig("results/fig4_dataset_comparison.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()
plt.close()
# print("  fig4_dataset_comparison.png saved.") # Commented out as files are not saved

# -- Figure 5: Combined figure for paper (Fig 1 + Fig 2 side by side)
fig5, (axL, axR) = plt.subplots(1, 2, figsize=(14, 5))

# Left - accuracy over time
for phase in ["clean", "drift", "recovery"]:
    xs = [i for i, p in enumerate(phases) if p == phase]
    ys = [accs[i] for i in xs]
    axL.plot(xs, ys, color=phase_colors[phase], linewidth=2, label=phase.capitalize())
axL.axhline(y=0.75, color="#BA7517", linestyle="--", linewidth=1.5, label="Threshold (75%)")
if trigger:
    axL.scatter([trigger], [accs[trigger]], color="#E24B4A", zorder=5, s=80, label="Retrain fired")
axL.set_ylim(0, 1.08)
axL.set_xlabel("Monitoring cycle", fontsize=11)
axL.set_ylabel("Rolling accuracy", fontsize=11)
axL.set_title("Accuracy over time (Breast Cancer, Run 1)", fontsize=11, fontweight="bold")
axL.legend(fontsize=9)
axL.grid(True, alpha=0.3)

# Right - comparison bars
bars2 = axR.bar(methods, values, color=colors, width=0.5, edgecolor="white", linewidth=1.5)
axR.axhline(y=75, color="#BA7517", linestyle="--", linewidth=1.5, label="Threshold (75%)")
for bar, val in zip(bars2, values):
    axR.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1.2,
             f"{val:.1f}%", ha="center", fontsize=11, fontweight="bold")
axR.set_ylim(0, 105)
axR.set_ylabel("Accuracy (%)", fontsize=11)
axR.set_title("Method comparison", fontsize=11, fontweight="bold")
axR.legend(fontsize=9)
axR.grid(True, alpha=0.3, axis="y")

plt.tight_layout()
plt.savefig("results/fig5_combined_paper.png", dpi=150, bbox_inches="tight", facecolor="white")
plt.show()
plt.close()
# print("  fig5_combined_paper.png saved.") # Commented out as files are not saved


# ==================================================================
# FINAL SUMMARY TABLE
# ==================================================================
print("\n" + "=" * 65)
print("  FINAL RESULTS SUMMARY")
print("=" * 65)
print(f"\n  {'Metric':<35} {'Breast Cancer':>15} {'Iris':>12}")
print(f"  {'-'*62}")
print(f"  {'Baseline accuracy (mean \u00b1 std)':<35} {bc_stats['baseline_mean']:.2%} \u00b1 {bc_stats['baseline_std']:.2%}    {iris_stats['baseline_mean']:.2%} \u00b1 {iris_stats['baseline_std']:.2%}")
print(f"  {'Min accuracy during drift (mean \u00b1 std)':<35} {bc_stats['drift_mean']:.2%} \u00b1 {bc_stats['drift_std']:.2%}    {iris_stats['drift_mean']:.2%} \u00b1 {iris_stats['drift_std']:.2%}")
print(f"  {'Recovery accuracy (mean \u00b1 std)':<35} {bc_stats['recovery_mean']:.2%} \u00b1 {bc_stats['recovery_std']:.2%}    {iris_stats['recovery_mean']:.2%} \u00b1 {iris_stats['recovery_std']:.2%}")
print(f"  {'Successful redeployments':<35} {bc_df['redeployed'].sum()}/5               {iris_df['redeployed'].sum()}/5")
print(f"  {'Human interventions':<35} {'0':>15} {'0':>12}")
print(f"\n  {'Comparison Method':<35} {'Accuracy':>10} {'Retrains':>10} {'Human':>8}")
print(f"  {'-'*65}")
print(f"  {'No monitoring (baseline)':<35} {no_mon_acc:.2%}      0          Yes")
print(f"  {'Scheduled retraining':<35} {sched_acc:.2%}      1          Yes")
print(f"  {'AutoHeal (proposed)':<35} {ah_acc:.2%}      {ah_retrain_count}           No")
print(f"\n  AutoHeal improvement vs no-monitor:     +{(ah_acc - no_mon_acc)*100:.1f} pp")
print(f"  AutoHeal improvement vs scheduled:      +{(ah_acc - sched_acc)*100:.1f} pp")
print("\n" + "=" * 65)
